# Generated by Django 5.2.17 on 2026-09-26 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('verdict', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ('Suspicious', 'Suspicious'), ('Benign', 'Benign'), ('Insufficient Data', 'Insufficient Data')], default='', max_length=30)),
                ('summary', models.TextField(blank=True, default='', help_text='Closure / investigation summary')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('correlation_uid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('closed_time', models.DateTimeField(blank=True, null=True)),
                ('severity_ai', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20)),
                ('confidence_ai', models.CharField(blank=True, default='', max_length=20)),
                ('priority_ai', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20)),
                ('verdict_ai', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('False Positive', 'False Positive'), ('True Positive', 'True Positive'), ('Suspicious', 'Suspicious'), ('Benign', 'Benign'), ('Insufficient Data', 'Insufficient Data')], default='', max_length=30)),
                ('investigation_report_ai_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('status', 'Status change'), ('link', 'Alert link'), ('system', 'System')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'db_table': 'case_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at', '-id'], name='case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-created_at'], name='case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['severity', '-created_at'], name='case_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'created_at'], name='case_event_idx'),
        ),
    ]
