# Generated by Django 5.2.17 on 2026-09-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('desc', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Unknown', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Suppressed', 'Suppressed'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('source', models.CharField(blank=True, default='manual', max_length=50)),
                ('source_uid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('rule_id', models.CharField(blank=True, default='', max_length=255)),
                ('rule_name', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_uid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('tactic', models.CharField(blank=True, default='', max_length=100)),
                ('technique', models.CharField(blank=True, default='', max_length=100)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cases.case')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='alert_created_idx'), models.Index(fields=['status', '-created_at'], name='alert_status_idx'), models.Index(fields=['severity', '-created_at'], name='alert_severity_idx')],
            },
        ),
    ]
