# Generated by Django 5.2.17 on 2026-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='iocs',
            field=models.JSONField(blank=True, default=list, help_text='regex-extracted [{type,value}] (deterministic)'),
        ),
    ]
