# Generated by Django 5.2.17 on 2026-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('local_feed', 'Local feed file (CSV)'), ('http_lookup', 'HTTP lookup (user-owned endpoint)')], default='local_feed', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrichment_providers',
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_value', models.CharField(db_index=True, max_length=255)),
                ('ioc_type', models.CharField(default='other', max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('verdict', models.CharField(choices=[('malicious', 'Malicious'), ('suspicious', 'Suspicious'), ('clean', 'Clean'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrichments',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['ioc_value', '-updated_at'], name='enrichment_ioc_idx')],
                'constraints': [models.UniqueConstraint(fields=('ioc_value', 'provider'), name='uniq_enrichment_ioc_provider')],
            },
        ),
    ]
