# Generated by Django 5.2.17 on 2026-09-26 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('extraction', 'Extraction'), ('manual', 'Manual'), ('playbook', 'Playbook')], default='extraction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='kb_created_idx'), models.Index(fields=['source', '-created_at'], name='kb_source_idx')],
            },
        ),
    ]
