# Generated by Django 5.2.17 on 2026-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, default='', max_length=300)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('gguf_path', models.CharField(blank=True, default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Model configuration',
            },
        ),
    ]
