# Generated by Django 5.2.17 on 2026-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='context_window',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
